# Generated by Django 4.2.30 on 2026-09-16 23:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_no', models.CharField(db_index=True, max_length=50, verbose_name='件名番号')),
                ('reception_no', models.CharField(db_index=True, max_length=50, verbose_name='受付番号')),
                ('date', models.DateField(db_index=True, verbose_name='報告日付')),
                ('title', models.CharField(max_length=200, verbose_name='件名')),
                ('address', models.CharField(blank=True, default='', max_length=300, verbose_name='住所')),
                ('description', models.TextField(verbose_name='業務内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
            ],
            options={
                'verbose_name': '業務報告',
                'verbose_name_plural': '業務報告一覧',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', '作成'), ('READ', '閲覧/ダウンロード'), ('UPDATE', '更新'), ('DELETE', '削除')], max_length=20, verbose_name='操作種別')),
                ('target_model', models.CharField(max_length=50, verbose_name='対象モデル')),
                ('target_id', models.CharField(max_length=50, verbose_name='対象ID')),
                ('details', models.TextField(blank=True, default='', verbose_name='詳細情報')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IPアドレス')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作日時')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作ユーザー')),
            ],
            options={
                'verbose_name': '操作ログ',
                'verbose_name_plural': '操作ログ一覧',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, verbose_name='保存ファイル名')),
                ('original_filename', models.CharField(max_length=255, verbose_name='オリジナルファイル名')),
                ('r2_key', models.CharField(max_length=500, unique=True, verbose_name='R2オブジェクトキー')),
                ('content_type', models.CharField(max_length=100, verbose_name='Content-Type')),
                ('file_size', models.BigIntegerField(verbose_name='ファイルサイズ(Bytes)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='アップロード日時')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='reports.report', verbose_name='対象報告')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL, verbose_name='アップロード者')),
            ],
            options={
                'verbose_name': '添付ファイル',
                'verbose_name_plural': '添付ファイル一覧',
            },
        ),
    ]
